kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: node:16
    commands:
      - yarn install
      - yarn run build
      - yarn run test
      - yarn run test:cjs
      - yarn run test:mjs
      - yarn run test:types
